name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: |
          chmod +x gradlew || true
          ./gradlew make makePluginsJson --no-build-cache || ./gradlew make --no-build-cache || true

      - name: Deploy to builds Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds # الفرع المستهدف
          folder: build # المجلد الناتج عن البناء لتوليد الروابط
          token: ${{ secrets.GITHUB_TOKEN }}
